name: ci
on:
  push:
    branches:
      - master
jobs:
  subsplit:
    runs-on : ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: true
          
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          
      - name: split
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          cd build
          echo "hehe"
          
          ls -al
          sudo chmod a+x git-subsplit.sh
          sudo cp git-subsplit.sh "$(git --exec-path)"/git-subsplit;
           echo "haha"
          ls -al $(git --exec-path)
          sudo sh split.sh
